### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by justbur** [noctuid/lispyville#11]
Thanks for this. I like it so far

I'm wondering if you were planning on putting this on melpa.

I'm also not clear on the lispy dependence. Does `lispy-mode` have to be active for the evil key bindings to work properly?

**Comment by noctuid** [comment]
Yes, I'm planning on adding it to melpa.

I mention this in the readme, but I could probably make it more clear. The provided commands/keybindings should not require `lispy-mode` to work correctly. There are some keybindings that are only useful when used with lispy though.

**Comment by justbur** [comment]
Right now I'm just trying to replace cleverparens and I don't want the
lispy insert bindings yet. That's what I wasn't sure about.

**Comment by noctuid** [comment]
Yeah that should work fine.

Though if you have lispy-mode disabled, you have to manually bind the lispy commands you want (e.g. `(` for auto-pairing). That said, you can also use `lispy-mode` without any of its "special" keybindings by using `lispy-set-key-theme` without `special` if you want.

**Comment by noctuid** [comment]
Okay, I've added a section in the readme to better address your question. I also made a pull request on melpa (see melpa/melpa#3997).

**Comment by justbur** [comment]
Thanks that clarifies things for me. It was more that I just wanted to replace cleverparens normal state bindings initially and had a bunch of conflicts with the lispy ones in insert state and my personal ones. I wasn't sure what if anything lispy-mode provided (besides key bindings).
