### ISSUE TITLE
lispyville-change cc undo takes two operations when there are leading spaces

### ISSUE THREAD

**Issue by sooheon** [noctuid/lispyville#13]
On a indented line, `cc` will delete the whole line and put cursor at indentation. But undoing this operation takes two steps.

**Comment by sooheon** [comment]
To reproduce:

```
(defvar foo
  |bar baz)
```

Type `cchello<Esc>u`. The first `u` will undo the "hello", but put cursor at column 0. It takes two `u`s to get back to initial state.

**Comment by noctuid** [comment]
Thanks for reporting. It should be fixed now.

**Comment by sooheon** [comment]
Thanks, it's fixed. Sorry I forgot to mention the setting of that variable!
