### ISSUE TITLE
Doesn't play well with general.el and general-key-dispatch

### ISSUE THREAD

**Issue by sriramkswamy** [noctuid/lispyville#14]
I ran into this problem when I was trying to use both lispyville and `general.el`. All the keybindings defined work except for the `general-key-dispatch` ones. For some reason, `co` would just put me in insert mode, like what `s` would normally do. It took me a while to isolate the package that caused the trouble.

Here's my actual configuration for lispyville and `general.el` -

    (use-package lispyville
      :ensure t		      ; ensure the package is present
      :demand t		      ; load the package immediately
      :diminish lispyville-mode   ; clean the modeline of this mode
      :diminish lispy-mode	      ; disable lispy mode also
      :config		      ; configuration to be loaded after package loading
      (with-eval-after-load 'lispyville	; once lispyville loads
        (lispyville-set-key-theme '(operators ; set the operators theme in normal and visual states
    				(escape insert)
    				(slurp/barf-lispy)))) ; set the escape theme in the insert state
      (add-hook 'emacs-lisp-mode-hook #'lispyville-mode)
      (add-hook 'lispyville-mode-hook #'lispy-mode))

    (use-package evil				; extensible vi layer - evil
    :ensure t				        ; ensure the package is present
    :demand t
    :general					; `general.el' maps
    (general-nmap :prefix sk--evil-global-leader  ; create a global leader map
		    "" '(nil :which-key "user prefix")
		    "q" '(evil-quit :which-key "quit window/emacs")
		    "k" '(evil-delete-buffer :which-key "kill buffer")
		    "a" (general-simulate-keys "C-x b" t "switch buffers")
		    "f" (general-simulate-keys "C-x C-f" t "find files")
		    "j" (general-simulate-keys "M-x" t "command")
		    "y" (general-simulate-keys "M-y" t "yank ring")
		    "x" (general-simulate-keys "C-h" t "help")
		    "w" 'save-buffer)
    (general-nmap "c" (general-key-dispatch 'evil-change
			"ow" 'toggle-word-wrap
			"c" 'evil-change-whole-line))
    (general-vmap "c" 'evil-change)
    (general-nmap "go" (general-simulate-keys "C-x C-e" t "eval"))
    (general-nmap "w" (general-simulate-keys "C-x o" t "other window"))
    (general-nmap "gz" (general-simulate-keys "C-x 1" t "only window"))
    (general-nmap "W" 'winner-undo)
    (general-nmap "gW" 'winner-redo)
    (general-nmap "gS" (general-simulate-keys "C-j" t "split line"))
    (general-nmap "gJ" 'evil-join)
    :init				    		; settings to be loaded before the package is loaded
    (setq evil-want-C-u-scroll t)		        ; scroll like Vim when in normal mode
    (setq evil-want-Y-yank-to-eol t)	        ; yank 'Y' like 'D' and 'C'
    :config				        ; settings after the package is loaded
    (setq evil-normal-state-modes (append evil-emacs-state-modes evil-normal-state-modes))
    (setq evil-emacs-state-modes nil)	        ; let there be no emacs state modes. add them all to normal state
    (evil-mode 1))			        ; turn on the Vi emulation

**Comment by noctuid** [comment]
Lispyville rebinds the `c` operator if you use `operator`s in the key theme. You need to make a new `general-key-dispatch` that falls back to `lispyville-change` and bind it in `lispyville-mode-map` after setting the key theme. For example:

```
(lispyville-set-key-theme ....)
...
(general-evil-define-key 'normal lispyville-mode-map
    "c" (general-key-dispatch #'lispyville-change
          "ow" #'toggle-word-wrap
          "c" #'lispyville-change-whole-line))
```
You don't need to rebind `c` in visual state like you do for `evil-change`  since the operators are bound in visual state as well by default (as pointed out in your comment).

Let me know if you encounter any problems with this, and I'll reopen the issue.

**Comment by sriramkswamy** [comment]
This works. Thank you!

**Comment by noctuid** [comment]
As an update for anyone who happens to read this issue, lispyville now uses command remapping and `general-key-dispatch` will automatically use remapped commands, so no extra configuration is necessary (i.e. if you bind `c` to `(general-key-dispatch #'evil-change...)` in `evil-normal-state-map`, it will fall back to using `lispyville-change` when `lispyville-mode` is active).
