### ISSUE TITLE
Default configuration not working at all under evil mode

### ISSUE THREAD

**Issue by bpstahlman** [noctuid/lispyville#15]
I have the following in my .emacs:
```
(require 'lispy)
(require 'lispyville)
(add-hook 'scheme-mode-hook #'lispy-mode)
(add-hook 'lispy-mode-hook #'lispyville-mode)
(require 'evil)
(evil-mode t)

```

When I open a .scm file, I have access to a few lispyville operators, but very little lispy functionality: e.g., stuff like `[`, `]`, and `lispy-flow` are missing, and most of the lispy bindings I see involve Control or Meta keys. Positioning point on a paren doesn't put me in lispy special. Disabling evil mode makes all the lispy bindings available, and allows me to get into lispy special. As I understand it, lispyville is meant to work under evil mode, so how do I make evil, lispyville and lispy work together?

Thanks,
Brett S.

**Comment by noctuid** [comment]
What is the behavior that you are expecting? Are the lispy keybindings not working in insert (or emacs) state? 

As for your question on the melpa pull request, you need to have lispy installed from melpa (not melpa stable).

**Comment by bpstahlman** [comment]
Was expecting to enter lispy special when I landed on a paren with `[` or `]`. But just a little bit ago, I discovered variable `lispyville-motions-put-into-special`, and realized I could get the behavior I was expecting by setting it to non-nil. I guess I'll need to read through the README a bit more to get a better feel for key themes and the relationship between lispy and lispyville. I was originally thinking of lispyville as just a sort of wrapper for lispy, but as I perused the README earlier, I realized that's an oversimplification, to say the least...

**Comment by noctuid** [comment]
Yes, lispyville doesn't add any new states or try to override normal state keys at special locations.

If you have any other questions or suggestions, feel free to make a new issue.

**Comment by bpstahlman** [comment]
Understood. I'm going to spend some time going through the lispyville and
lispy documentation, playing around in emacs, trying to figure out what
configuration works best for me. No doubt, I'll have more questions at some
point. ;-)

Thanks,
Brett S.
