### ISSUE TITLE
Odd behavior when yanking/pasting with block selection

### ISSUE THREAD

**Issue by dieggsy** [noctuid/lispyville#31]
For example, with lispyville-mode on, if I have:
```emacs-lisp
"
123 456 789
123 456 789
"
```
And I highlight the 456 column and delete it (with point at top 4, `C-v 3l j d`), then try to paste them _after_ the 789 column (with point at top 9, `p`) I get:

```emacs-lisp
"
123 789456 
456 
123 789
"
```

If repeat all these steps with lispyville-mode off, I get the expected:

```emacs-lisp
"
123 789456
123 789456
"
```

**Comment by noctuid** [comment]
This should be fixed on the `31` branch.

**Comment by noctuid** [comment]
This is fixed now. Please open a new issue if you find any strange behavior with any other operators (particularly linewise) after this change.
