### ISSUE TITLE
Slurping/Barfing strings (" characters)

### ISSUE THREAD

**Issue by Hoekstraa** [noctuid/lispyville#314]
I've enjoyed using this mode so far, however I'd really like to be able to Slurp/Barf strings as well.
So support for `"` and `'` characters would be grand.
I'm having a hard time finding where and how I could modify the set of allowed characters that can be Slurped/Barfed. And I understand that strings might require some extra work as it might be harder to discern which belong together compared to `(`,`[`,`{` .
However, this is the biggest thing I've been missing and would love any info regarding this.

**Comment by noctuid** [comment]
Lispyville is just using lispy for slurp/barf, and lispy does not support slurping and barfing with strings.  It's unlikely lispyville will support this in the future unless lispy does.  See https://github.com/abo-abo/lispy/issues/305 There is a kind of workaround given there (unquoting then slurping a region and requoting), but it's not as quick

**Comment by Hoekstraa** [comment]
Ah, I see.
I feel stupid now for not digging a little deeper myself haha.
I'll try the methods described in the linked issue.
Thank you for the help!
