### ISSUE TITLE
Inifinite loop with a combination of end-of-line comments and comments with parentheses

### ISSUE THREAD

**Issue by Ambrevar** [noctuid/lispyville#32]
Sorry for the very unspecific title...

In the following block,

```elisp
(lispyville-set-key-theme
   '(operators
     mark-toggle             ; foo
     ;; bar (baz)
     ))
```

a `yy` or a `dd` on the "bar" line will loop indefinitely.
So will `yap` and `dap` anywhere in the block.

**Comment by noctuid** [comment]
See #30. This is an issue with `lispy--bounds-comment` not working correctly with these comments.

**Comment by Ambrevar** [comment]
I was suspecting those two were related :)

**Comment by noctuid** [comment]
This should be fixed with the latest lispy.

**Comment by Ambrevar** [comment]
Fantastic!
