### ISSUE TITLE
dd bug

### ISSUE THREAD

**Issue by justbur** [noctuid/lispyville#34]
This seems to have been introduced recently. Here's a test case

```elisp
(let ((a 1)
      (b 3))
  (setq c a))
(func 1)
```
`dd` on the second line gets me
```elisp
(let ((a 1))  (setq c a))


(func 1)
```
There's an extra join line in there, pulling the `setq` expression up a line. `dd` on the original third line gets me
```elisp
(let ((a 1)
      (b 3)))(func 1)
```
I couldn't think of anything in my settings that would cause this, and I don't remember this behavior happening until recently.

**Comment by noctuid** [comment]
I was aware that there were still issues with `dd` after 39d88b9, so thank you for the bug report. Sorry for the trouble; this issue should be fixed now. Let me know if you encounter any other issues with `dd`. There is a related issue that I'll fix for `cc` when I get the chance.

**Comment by justbur** [comment]
No problem and thanks
