### ISSUE TITLE
Can you clarify the indentation logic behind prettifier?

### ISSUE THREAD

**Issue by NightMachinary** [noctuid/lispyville#35]
I have asked about the issue here:
https://stackoverflow.com/questions/49499245/what-are-the-rules-behind-the-typical-indenting-conventions-of-lisp?noredirect=1#comment86002619_49499245

Here is a screenshot of the question:
![image](https://user-images.githubusercontent.com/36224762/37929090-37ee6ec4-3154-11e8-8a3e-2cb544766d58.png)

**Comment by noctuid** [comment]
That's how `if` indentation works in elisp. It's because `if` can have multiple else forms in elisp unlike in common lisp.
