### ISSUE TITLE
Quotes are not properly deleted

### ISSUE THREAD

**Issue by sooheon** [noctuid/lispyville#4]
`"foo bar"` and `dd` `D`, etc. will leave one hanging quote.

**Comment by noctuid** [comment]
Sorry about that. Looks like this problem was introduced when I added `lispy-safe-actions-ignore-strings`. Fortunately, it looks like it's a one line fix. I made a pull request to lispy, so let me know if you have any other problems after it is merged.

**Comment by sooheon** [comment]
Can confirm, issue is fixed. Another edge case I found is that the delete operator has trouble on the very last line of buffer. Trying to `dd` the very last line gives me `lispy--find-unmatched-delimiters: Invalid search bound (wrong side of point)`. If a sexp is on the very last line, the delimiters are not deleted, only the contents.

**Comment by noctuid** [comment]
Let me know if that fixes it.

**Comment by sooheon** [comment]
Yep, it's been fixed. Thanks!
