### ISSUE TITLE
Splicing operator 'x' deletes wrong set of parens from end

### ISSUE THREAD

**Issue by yuhan0** [noctuid/lispyville#47]
```
;;            AB
(defn foo [bar])
```

With the cursor at position B (over the round closing paren) pressing 'x' for `lispyville-delete-char-or-splice` removes the square brackets instead. This issue occurs with all types of brackets (round, square or curly), but not string quotes.

**Comment by noctuid** [comment]
Thanks for reporting. It should be fixed now.
