### ISSUE TITLE
M-n M-p more appropriate than M-j M-k for lispyville-drag?

### ISSUE THREAD

**Issue by sooheon** [noctuid/lispyville#5]
This isn't an issue, just a suggestion, but don't M-j M-k have pretty useful keybinds for lisps? C-j, M-j, C-M-j etc. are nicely parallel, and so are C-k and M-k. M-n and M-p are free though.

**Comment by noctuid** [comment]
The theme is meant to mirror evil-cleverparen's keybindings. I can add another one where they are bound to `M-n` and `M-p` (any suggestions for a name?).

That said, they aren't bound in insert state (by default) which is where I might normally use `lispy-split` and `lispy-kill-sentence` (though they could be useful in normal state too).

**Comment by noctuid** [comment]
I'm going to leave the key theme as is and let users make alternate keybindings if they wish.
