### ISSUE TITLE
[question] How to evil-define-motion something like lispyville-backward-up-list that's paren-safe?

### ISSUE THREAD

**Issue by JJPandari** [noctuid/lispyville#53]
I want to move to any `[]` `()` `{}` in normal state in a single key(`(`), in any programming language, so I defined 2 functions using `evil-define-motion`. The forward one works well, but the backward one, say, moves to(right before) the closest `(` correctly, but also deletes it when I type `d(`, even if I use `:type exclusive`. How to make it behave like `lispyville-backward-up-list`? Here's the code:  

```lisp
(evil-define-motion backward-bracket (count)
  "Move backward to a (, [ or {."
  :type exclusive
  (setq count (or count 1))
  (search-backward-regexp "[([{]" nil t count))
```

**Comment by noctuid** [comment]
It's the operator code that matters for this. As long as you have d bound to lispyville-delete, it shouldn't matter what motion is used. Are you trying this in a mode where d is still bound to evil-delete?

lispyville-mode should still work in non-lisp modes, but there is some lisp specific logic for trailing paren placement, for example. If you encounter issues with enabling lispyville-mode in non-lisp modes or binding the safe operators in them, feel free to make another issue.

**Comment by JJPandari** [comment]
> Are you trying this in a mode where d is still bound to evil-delete?

yes.

> If you encounter issues with enabling lispyville-mode in non-lisp modes or binding the safe operators in them, feel free to make another issue.

Not sure if we should really bother making lispyville working in non-lispy modes, but since you say so, I'll try it out and report unwanted behaviours.
