### ISSUE TITLE
Prettify escapes atoms in Clojure that starts with "."

### ISSUE THREAD

**Issue by thiagokokada** [noctuid/lispyville#58]
In Clojure, the following atom is valid:

```clojure
:.some-atom
```

However, calling `lispyville-prettify` in this atom results in:

```clojure
:\.some-atom
```

That is not a valid atom.

**Comment by noctuid** [comment]
This is handled by lispy. Try updating lispy if you are on an older version, and if the problem still happens, make an issue on the lispy repo.

**Comment by thiagokokada** [comment]
@noctuid Ok. Thanks.

**Comment by thiagokokada** [comment]
Will keep this issue open just to track it with issue in Lispy.

**Comment by thiagokokada** [comment]
Fixed by https://github.com/abo-abo/lispy/commit/aa9feb855b24f29e0c6cd0c3a68a83a91fd63182.

**Comment by thiagokokada** [comment]
Fixed by https://github.com/abo-abo/lispy/commit/aa9feb855b24f29e0c6cd0c3a68a83a91fd63182.
