### ISSUE TITLE
lispyville-change word is too greedy

### ISSUE THREAD

**Issue by aaronjensen** [noctuid/lispyville#61]
`lispyville-change` when used with `w` will delete any spaces after the atom being changed. Worse, it will delete `'` on a following list. For example:

```lisp
;; initially (| is point)
(my-|word '(a list))

;; cw (actual)
(my-|(a list))

;; cw (expected)
(my-| '(a list))
```

**edit** another way to say this, is it would be great if `evil-want-change-word-to-end` was respected.

**Comment by noctuid** [comment]
This already works for me. You have `evil-want-change-word-to-end` as t? I'll try updating to the latest evil version; any other info you can give me would help. `evil-change` works as expected?

**Comment by aaronjensen** [comment]
@noctuid Yes, it works and yes that's set to `t`. Do you have `atom-movement` set? Here's my config:

```elisp
(use-package lispyville
  :hook (lispy-mode . lispyville-mode)
  :config
  (lispyville-set-key-theme '(operators
                              prettify
                              text-objects
                              atom-movement
                              slurp/barf-lispy
                              wrap
                              additional
                              additional-insert
                              additional-movement
                              (additional-wrap normal insert)
                              escape)))
```

**Comment by noctuid** [comment]
Oh okay. You want the atom motion to respect `evil-want-change-word-to-end`. I can do that or add a lispyville option for it. I'll try to do that next week.

**Comment by aaronjensen** [comment]
Much appreciated. I'm now using `(atom-movement t)`, but it'd still be good to have that work that way. I just refuse to use `ce`, it's way too awkward to type 😄

**Comment by noctuid** [comment]
Okay, I've added `lispyville-want-change-atom-to-end` which defaults to using the value of `evil-want-change-word-to-end`. Please test.

**Comment by aaronjensen** [comment]
Seems to work well, thank you!
