### ISSUE TITLE
Deleting Lines with Strings

### ISSUE THREAD

**Issue by seanirby** [noctuid/lispyville#7]
Hey, really enjoying lispyville so far :).

I notice some weird behavior whenever I ```dd``` on a single line of strings.

For instance, deleting the line containing ```"1234" "5678"``` gets transformed to ```"``` which is unexpected.  I would expect the whole line to get deleted or maybe have it result in ```""``` which would match the behavior for parens.   The code actually does the latter until it reaches this section 
https://github.com/noctuid/lispyville/blob/master/lispyville.el#L373-L376

Just curious what the reasoning is for that.  Thanks

**Comment by noctuid** [comment]
The expected behavior is to just have everything deleted since the delimiters on the line are all matched. This is what happens for me. My guess is that this is the same issue as #4 in which case you need to update `lispy` itself. Let me know if that's not the problem.

**Comment by seanirby** [comment]
Yeah that fixed it.  Thanks
