### ISSUE TITLE
lispyville-delete will unbalance ending parens after a comment

### ISSUE THREAD

**Issue by sooheon** [noctuid/lispyville#8]
from 

```
(foo
 ;; bar
 |baz)
```

`dd` gives me

```
(foo
 ;; bar)
```

I didn't notice this before, is this a recent change?

**Comment by noctuid** [comment]
Yeah I think it might be, but I'm not sure. I just noticed this yesterday. I'll look into it.

**Comment by noctuid** [comment]
`dd` specifically is fixed now. I should maybe also prevent closing delimiters being pulled into comments if the user tries to delete the following:
```
(a
;; ~b
c)|
```

**Comment by justbur** [comment]
Here's a similar problem with comments that I just ran into. Case 1 is fine, but Case 2 gets you into a situation with unbalanced parens
```elisp
;; CASE 1
(let ((a 1)
      (b 1))
  (+ a b))

;; dd on first line
((      (b 1))
  (+ a b))

;; CASE 2
(let (;; (a 1)
      (b 1))
  (+ a b))

;; dd on first line
(      (b 1))
  (+ a b))
```

**Comment by noctuid** [comment]
Thanks for reporting. I made a pull request to lispy to fix the issue.

**Comment by justbur** [comment]
Thank you

**Comment by noctuid** [comment]
With the latest commit of lispy, this should no longer be an issue for the previously mentioned case.
