### ISSUE TITLE
lispyville-delete called with `dG` acts strangely

### ISSUE THREAD

**Issue by sooheon** [noctuid/lispyville#9]
In a buffer with multiple lines, calling `dG` will leave the cursor in the middle of the screen in a position it cannot be in (where no lines exist). Then pressing any other key moves the cursor back to last real line, but there are trailing whitespace in the line above.

**Comment by noctuid** [comment]
Thanks for reporting. The trailing whitespace issue should be fixed. I couldn't replicate the first problem mentioned. Let me know if it is still happening for you.

**Comment by sooheon** [comment]
Cool, both are fixed for me. Really strangely, after `dG`, emacs will try to complete the last word before point. This only happens with lispyville-mode on.

**Comment by noctuid** [comment]
You mean a word on a previous line? Could you give an example?

**Comment by sooheon** [comment]
Starting from:

```
foo bar bas
|
quux
```

dG leaves me with:

<img width="697" alt="screen shot 2016-05-24 at 4 28 02 pm" src="https://cloud.githubusercontent.com/assets/302945/15495707/802f390a-21cc-11e6-8bf8-e7ab8a725eee.png">

**Comment by noctuid** [comment]
Do you happen to have `indent-for-tab-command` advised?

**Comment by noctuid** [comment]
Okay, it should be fixed now.

**Comment by sooheon** [comment]
Thank you! The cursor now correctly goes to bol as well.
